#!/bin/bash

# Let's Encrypt manual mode (for Reverse Proxy sites)
source /opt/webinoly/lib/general
[[ -n $(conf_read temp-path) ]] && sslpath=$(conf_read temp-path) || sslpath="/var/www/.webinoly"
sudo mkdir -p $sslpath/.well-known/acme-challenge
sudo touch $sslpath/.well-known/acme-challenge/$CERTBOT_TOKEN
sudo echo $CERTBOT_VALIDATION > $sslpath/.well-known/acme-challenge/$CERTBOT_TOKEN
